build: false

services:
  - postgresql

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      PIP_PSYCOPG2: "win32-py27"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      PIP_PSYCOPG2: "win32-py34"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      PIP_PSYCOPG2: "win32-py34"

init:
  - "PATH=C:\\Program Files\\PostgreSQL\\9.3\\bin\\;%PATH%"
  - "SET PGUSER=postgres"
  - "SET PGPASSWORD=Password12!"
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install git+https://github.com/nwcell/psycopg2-windows.git@%PIP_PSYCOPG2%#egg=psycopg2"
  - "%PYTHON%/Scripts/pip.exe install -r requirements-win.txt"
  - "%PYTHON%/Scripts/pip.exe install ."

test_script:
  - "%PYTHON%/Scripts/py.test"
  - "cd tests"
  - "%PYTHON%/Scripts/behave"
